<?php

/*
 * Bear Framework
 * http://bearframework.com
 * Copyright (c) Ivo Petkov
 * Free to use under the MIT license.
 */

$classes = [
    'BearFramework' => 'src/BearFramework.php',
    'BearFramework\App\Addon' => 'src/App/Addon.php',
    'BearFramework\App\Addons' => 'src/App/Addons.php',
    'BearFramework\App\Assets' => 'src/App/Assets.php',
    'BearFramework\App\Assets\BeforeGetDetailsEventDetails' => 'src/App/Assets/BeforeGetDetailsEventDetails.php',
    'BearFramework\App\Assets\BeforeGetURLEventDetails' => 'src/App/Assets/BeforeGetURLEventDetails.php',
    'BearFramework\App\Assets\BeforePrepareEventDetails' => 'src/App/Assets/BeforePrepareEventDetails.php',
    'BearFramework\App\Assets\GetDetailsEventDetails' => 'src/App/Assets/GetDetailsEventDetails.php',
    'BearFramework\App\Assets\GetURLEventDetails' => 'src/App/Assets/GetURLEventDetails.php',
    'BearFramework\App\Assets\PrepareEventDetails' => 'src/App/Assets/PrepareEventDetails.php',
    'BearFramework\App\BeforeSendResponseEventDetails' => 'src/App/BeforeSendResponseEventDetails.php',
    'BearFramework\App\CacheItem' => 'src/App/CacheItem.php',
    'BearFramework\App\CacheRepository' => 'src/App/CacheRepository.php',
    'BearFramework\App\Cache\ItemChangeEventDetails' => 'src/App/Cache/ItemChangeEventDetails.php',
    'BearFramework\App\Cache\ItemDeleteEventDetails' => 'src/App/Cache/ItemDeleteEventDetails.php',
    'BearFramework\App\Cache\ItemExistsEventDetails' => 'src/App/Cache/ItemExistsEventDetails.php',
    'BearFramework\App\Cache\ItemGetEventDetails' => 'src/App/Cache/ItemGetEventDetails.php',
    'BearFramework\App\Cache\ItemGetValueEventDetails' => 'src/App/Cache/ItemGetValueEventDetails.php',
    'BearFramework\App\Cache\ItemRequestEventDetails' => 'src/App/Cache/ItemRequestEventDetails.php',
    'BearFramework\App\Cache\ItemSetEventDetails' => 'src/App/Cache/ItemSetEventDetails.php',
    'BearFramework\App\Classes' => 'src/App/Classes.php',
    'BearFramework\App\Config' => 'src/App/Config.php',
    'BearFramework\App\Context' => 'src/App/Context.php',
    'BearFramework\App\Context\Assets' => 'src/App/Context/Assets.php',
    'BearFramework\App\Context\Classes' => 'src/App/Context/Classes.php',
    'BearFramework\App\Contexts' => 'src/App/Contexts.php',
    'BearFramework\App\Data\BeforeGetListEventDetails' => 'src/App/Data/BeforeGetListEventDetails.php',
    'BearFramework\App\Data\DataLockedException' => 'src/App/Data/DataLockedException.php',
    'BearFramework\App\Data\GetListEventDetails' => 'src/App/Data/GetListEventDetails.php',
    'BearFramework\App\Data\ItemAppendEventDetails' => 'src/App/Data/ItemAppendEventDetails.php',
    'BearFramework\App\Data\ItemBeforeAppendEventDetails' => 'src/App/Data/ItemBeforeAppendEventDetails.php',
    'BearFramework\App\Data\ItemBeforeDeleteEventDetails' => 'src/App/Data/ItemBeforeDeleteEventDetails.php',
    'BearFramework\App\Data\ItemBeforeDeleteMetadataEventDetails' => 'src/App/Data/ItemBeforeDeleteMetadataEventDetails.php',
    'BearFramework\App\Data\ItemBeforeDuplicateEventDetails' => 'src/App/Data/ItemBeforeDuplicateEventDetails.php',
    'BearFramework\App\Data\ItemBeforeExistsEventDetails' => 'src/App/Data/ItemBeforeExistsEventDetails.php',
    'BearFramework\App\Data\ItemBeforeGetEventDetails' => 'src/App/Data/ItemBeforeGetEventDetails.php',
    'BearFramework\App\Data\ItemBeforeGetMetadataEventDetails' => 'src/App/Data/ItemBeforeGetMetadataEventDetails.php',
    'BearFramework\App\Data\ItemBeforeGetValueEventDetails' => 'src/App/Data/ItemBeforeGetValueEventDetails.php',
    'BearFramework\App\Data\ItemBeforeGetValueLengthEventDetails' => 'src/App/Data/ItemBeforeGetValueLengthEventDetails.php',
    'BearFramework\App\Data\ItemBeforeRenameEventDetails' => 'src/App/Data/ItemBeforeRenameEventDetails.php',
    'BearFramework\App\Data\ItemBeforeSetEventDetails' => 'src/App/Data/ItemBeforeSetEventDetails.php',
    'BearFramework\App\Data\ItemBeforeSetMetadataEventDetails' => 'src/App/Data/ItemBeforeSetMetadataEventDetails.php',
    'BearFramework\App\Data\ItemBeforeGetStreamWrapperEventDetails' => 'src/App/Data/ItemBeforeGetStreamWrapperEventDetails.php',
    'BearFramework\App\Data\ItemBeforeSetValueEventDetails' => 'src/App/Data/ItemBeforeSetValueEventDetails.php',
    'BearFramework\App\Data\ItemChangeEventDetails' => 'src/App/Data/ItemChangeEventDetails.php',
    'BearFramework\App\Data\ItemDeleteEventDetails' => 'src/App/Data/ItemDeleteEventDetails.php',
    'BearFramework\App\Data\ItemDeleteMetadataEventDetails' => 'src/App/Data/ItemDeleteMetadataEventDetails.php',
    'BearFramework\App\Data\ItemDuplicateEventDetails' => 'src/App/Data/ItemDuplicateEventDetails.php',
    'BearFramework\App\Data\ItemExistsEventDetails' => 'src/App/Data/ItemExistsEventDetails.php',
    'BearFramework\App\Data\ItemGetEventDetails' => 'src/App/Data/ItemGetEventDetails.php',
    'BearFramework\App\Data\ItemGetMetadataEventDetails' => 'src/App/Data/ItemGetMetadataEventDetails.php',
    'BearFramework\App\Data\ItemGetValueEventDetails' => 'src/App/Data/ItemGetValueEventDetails.php',
    'BearFramework\App\Data\ItemGetValueLengthEventDetails' => 'src/App/Data/ItemGetValueLengthEventDetails.php',
    'BearFramework\App\Data\ItemRenameEventDetails' => 'src/App/Data/ItemRenameEventDetails.php',
    'BearFramework\App\Data\ItemRequestEventDetails' => 'src/App/Data/ItemRequestEventDetails.php',
    'BearFramework\App\Data\ItemSetEventDetails' => 'src/App/Data/ItemSetEventDetails.php',
    'BearFramework\App\Data\ItemSetMetadataEventDetails' => 'src/App/Data/ItemSetMetadataEventDetails.php',
    'BearFramework\App\Data\ItemSetValueEventDetails' => 'src/App/Data/ItemSetValueEventDetails.php',
    'BearFramework\App\DataCacheDriver' => 'src/App/DataCacheDriver.php',
    'BearFramework\App\DataItem' => 'src/App/DataItem.php',
    'BearFramework\App\DataRepository' => 'src/App/DataRepository.php',
    'BearFramework\EventsTrait' => 'src/EventsTrait.php',
    'BearFramework\App\FileDataDriver' => 'src/App/FileDataDriver.php',
    'BearFramework\App\FileDataItemStreamWrapper' => 'src/App/FileDataItemStreamWrapper.php',
    'BearFramework\App\FileLogger' => 'src/App/FileLogger.php',
    'BearFramework\App\ICacheDriver' => 'src/App/ICacheDriver.php',
    'BearFramework\App\IDataDriver' => 'src/App/IDataDriver.php',
    'BearFramework\App\IDataItemStreamWrapper' => 'src/App/IDataItemStreamWrapper.php',
    'BearFramework\App\ILogger' => 'src/App/ILogger.php',
    'BearFramework\App\Logs' => 'src/App/Logs.php',
    'BearFramework\App\MemoryDataDriver' => 'src/App/MemoryDataDriver.php',
    'BearFramework\App\NullCacheDriver' => 'src/App/NullCacheDriver.php',
    'BearFramework\App\NullDataDriver' => 'src/App/NullDataDriver.php',
    'BearFramework\App\NullDataItemStreamWrapper' => 'src/App/NullDataItemStreamWrapper.php',
    'BearFramework\App\NullLogger' => 'src/App/NullLogger.php',
    'BearFramework\App\Request' => 'src/App/Request.php',
    'BearFramework\App\Request\Cookie' => 'src/App/Request/Cookie.php',
    'BearFramework\App\Request\Cookies' => 'src/App/Request/Cookies.php',
    'BearFramework\App\Request\FormDataItem' => 'src/App/Request/FormDataItem.php',
    'BearFramework\App\Request\FormDataFileItem' => 'src/App/Request/FormDataFileItem.php',
    'BearFramework\App\Request\FormData' => 'src/App/Request/FormData.php',
    'BearFramework\App\Request\Header' => 'src/App/Request/Header.php',
    'BearFramework\App\Request\Headers' => 'src/App/Request/Headers.php',
    'BearFramework\App\Request\Path' => 'src/App/Request/Path.php',
    'BearFramework\App\Request\QueryItem' => 'src/App/Request/QueryItem.php',
    'BearFramework\App\Request\Query' => 'src/App/Request/Query.php',
    'BearFramework\App\Response' => 'src/App/Response.php',
    'BearFramework\App\Response\Cookie' => 'src/App/Response/Cookie.php',
    'BearFramework\App\Response\Cookies' => 'src/App/Response/Cookies.php',
    'BearFramework\App\Response\FileReader' => 'src/App/Response/FileReader.php',
    'BearFramework\App\Response\HTML' => 'src/App/Response/HTML.php',
    'BearFramework\App\Response\Header' => 'src/App/Response/Header.php',
    'BearFramework\App\Response\Headers' => 'src/App/Response/Headers.php',
    'BearFramework\App\Response\JSON' => 'src/App/Response/JSON.php',
    'BearFramework\App\Response\NotFound' => 'src/App/Response/NotFound.php',
    'BearFramework\App\Response\PermanentRedirect' => 'src/App/Response/PermanentRedirect.php',
    'BearFramework\App\Response\TemporaryRedirect' => 'src/App/Response/TemporaryRedirect.php',
    'BearFramework\App\Response\TemporaryUnavailable' => 'src/App/Response/TemporaryUnavailable.php',
    'BearFramework\App\Response\Text' => 'src/App/Response/Text.php',
    'BearFramework\App\Routes' => 'src/App/Routes.php',
    'BearFramework\App\SendResponseEventDetails' => 'src/App/SendResponseEventDetails.php',
    'BearFramework\App\Shortcuts' => 'src/App/Shortcuts.php',
    'BearFramework\App\StringDataItemStreamWrapper' => 'src/App/StringDataItemStreamWrapper.php',
    'BearFramework\App\URLs' => 'src/App/URLs.php',
    'BearFramework\Addon' => 'src/Addon.php',
    'BearFramework\Addons' => 'src/Addons.php',
    'BearFramework\App' => 'src/App.php',
    'BearFramework\DataList' => 'src/DataList.php',
    'BearFramework\DataList\Context' => 'src/DataList/Context.php',
    'BearFramework\DataList\FilterAction' => 'src/DataList/FilterAction.php',
    'BearFramework\DataList\FilterByAction' => 'src/DataList/FilterByAction.php',
    'BearFramework\DataList\MapAction' => 'src/DataList/MapAction.php',
    'BearFramework\DataList\ReverseAction' => 'src/DataList/ReverseAction.php',
    'BearFramework\DataList\ShuffleAction' => 'src/DataList/ShuffleAction.php',
    'BearFramework\DataList\SliceAction' => 'src/DataList/SliceAction.php',
    'BearFramework\DataList\SlicePropertiesAction' => 'src/DataList/SlicePropertiesAction.php',
    'BearFramework\DataList\SortAction' => 'src/DataList/SortAction.php',
    'BearFramework\DataList\SortByAction' => 'src/DataList/SortByAction.php',
    'BearFramework\DataObject' => 'src/DataObject.php',
    'BearFramework\Internal\DataStreamWrapper' => 'src/Internal/DataStreamWrapper.php',
    'BearFramework\Internal\ErrorHandler' => 'src/Internal/ErrorHandler.php',
    'BearFramework\Internal\Utilities' => 'src/Internal/Utilities.php',
];

spl_autoload_register(function ($class) use ($classes) {
    if (isset($classes[$class])) {
        require __DIR__ . '/' . $classes[$class];
    }
}, true);
