<?php

/*
 * Bear Framework
 * http://bearframework.com
 * Copyright (c) Ivo Petkov
 * Free to use under the MIT license.
 */

$classes = [
    'BearFramework' => 'src/BearFramework.php',
    'BearFramework\App\Addon' => 'src/App/Addon.php',
    'BearFramework\App\AddonsRepository' => 'src/App/AddonsRepository.php',
    'BearFramework\App\Assets' => 'src/App/Assets.php',
    'BearFramework\App\Assets\BeforeGetDetailsEvent' => 'src/App/Assets/BeforeGetDetailsEvent.php',
    'BearFramework\App\Assets\BeforeGetUrlEvent' => 'src/App/Assets/BeforeGetUrlEvent.php',
    'BearFramework\App\Assets\BeforePrepareEvent' => 'src/App/Assets/BeforePrepareEvent.php',
    'BearFramework\App\Assets\GetDetailsEvent' => 'src/App/Assets/GetDetailsEvent.php',
    'BearFramework\App\Assets\GetUrlEvent' => 'src/App/Assets/GetUrlEvent.php',
    'BearFramework\App\Assets\PrepareEvent' => 'src/App/Assets/PrepareEvent.php',
    'BearFramework\App\BeforeSendResponseEvent' => 'src/App/BeforeSendResponseEvent.php',
    'BearFramework\App\CacheItem' => 'src/App/CacheItem.php',
    'BearFramework\App\CacheRepository' => 'src/App/CacheRepository.php',
    'BearFramework\App\Cache\ClearEvent' => 'src/App/Cache/ClearEvent.php',
    'BearFramework\App\Cache\ItemChangeEvent' => 'src/App/Cache/ItemChangeEvent.php',
    'BearFramework\App\Cache\ItemDeleteEvent' => 'src/App/Cache/ItemDeleteEvent.php',
    'BearFramework\App\Cache\ItemExistsEvent' => 'src/App/Cache/ItemExistsEvent.php',
    'BearFramework\App\Cache\ItemGetEvent' => 'src/App/Cache/ItemGetEvent.php',
    'BearFramework\App\Cache\ItemGetValueEvent' => 'src/App/Cache/ItemGetValueEvent.php',
    'BearFramework\App\Cache\ItemRequestEvent' => 'src/App/Cache/ItemRequestEvent.php',
    'BearFramework\App\Cache\ItemSetEvent' => 'src/App/Cache/ItemSetEvent.php',
    'BearFramework\App\ClassesRepository' => 'src/App/ClassesRepository.php',
    'BearFramework\App\Config' => 'src/App/Config.php',
    'BearFramework\App\Context' => 'src/App/Context.php',
    'BearFramework\App\Context\Assets' => 'src/App/Context/Assets.php',
    'BearFramework\App\Context\Classes' => 'src/App/Context/Classes.php',
    'BearFramework\App\ContextsRepository' => 'src/App/ContextsRepository.php',
    'BearFramework\App\Data\DataLockedException' => 'src/App/Data/DataLockedException.php',
    'BearFramework\App\Data\GetListEvent' => 'src/App/Data/GetListEvent.php',
    'BearFramework\App\Data\ItemAppendEvent' => 'src/App/Data/ItemAppendEvent.php',
    'BearFramework\App\Data\ItemChangeEvent' => 'src/App/Data/ItemChangeEvent.php',
    'BearFramework\App\Data\ItemDeleteEvent' => 'src/App/Data/ItemDeleteEvent.php',
    'BearFramework\App\Data\ItemDeleteMetadataEvent' => 'src/App/Data/ItemDeleteMetadataEvent.php',
    'BearFramework\App\Data\ItemDuplicateEvent' => 'src/App/Data/ItemDuplicateEvent.php',
    'BearFramework\App\Data\ItemExistsEvent' => 'src/App/Data/ItemExistsEvent.php',
    'BearFramework\App\Data\ItemGetEvent' => 'src/App/Data/ItemGetEvent.php',
    'BearFramework\App\Data\ItemGetMetadataEvent' => 'src/App/Data/ItemGetMetadataEvent.php',
    'BearFramework\App\Data\ItemGetMetadataListEvent' => 'src/App/Data/ItemGetMetadataListEvent.php',
    'BearFramework\App\Data\ItemGetValueEvent' => 'src/App/Data/ItemGetValueEvent.php',
    'BearFramework\App\Data\ItemRenameEvent' => 'src/App/Data/ItemRenameEvent.php',
    'BearFramework\App\Data\ItemRequestEvent' => 'src/App/Data/ItemRequestEvent.php',
    'BearFramework\App\Data\ItemSetEvent' => 'src/App/Data/ItemSetEvent.php',
    'BearFramework\App\Data\ItemSetMetadataEvent' => 'src/App/Data/ItemSetMetadataEvent.php',
    'BearFramework\App\Data\ItemSetValueEvent' => 'src/App/Data/ItemSetValueEvent.php',
    'BearFramework\App\DataCacheDriver' => 'src/App/DataCacheDriver.php',
    'BearFramework\App\DataItem' => 'src/App/DataItem.php',
    'BearFramework\App\DataRepository' => 'src/App/DataRepository.php',
    'BearFramework\App\Event' => 'src/App/Event.php',
    'BearFramework\App\EventsTrait' => 'src/App/EventsTrait.php',
    'BearFramework\App\FileDataDriver' => 'src/App/FileDataDriver.php',
    'BearFramework\App\FileDataItemStreamWrapper' => 'src/App/FileDataItemStreamWrapper.php',
    'BearFramework\App\FileLogger' => 'src/App/FileLogger.php',
    'BearFramework\App\Internal\DataItemStreamWrapper' => 'src/App/Internal/DataItemStreamWrapper.php',
    'BearFramework\App\Internal\ErrorHandler' => 'src/App/Internal/ErrorHandler.php',
    'BearFramework\App\ICacheDriver' => 'src/App/ICacheDriver.php',
    'BearFramework\App\IDataDriver' => 'src/App/IDataDriver.php',
    'BearFramework\App\IDataItemStreamWrapper' => 'src/App/IDataItemStreamWrapper.php',
    'BearFramework\App\ILogger' => 'src/App/ILogger.php',
    'BearFramework\App\LogsRepository' => 'src/App/LogsRepository.php',
    'BearFramework\App\Request' => 'src/App/Request.php',
    'BearFramework\App\Request\Cookie' => 'src/App/Request/Cookie.php',
    'BearFramework\App\Request\CookiesRepository' => 'src/App/Request/CookiesRepository.php',
    'BearFramework\App\Request\FormDataItem' => 'src/App/Request/FormDataItem.php',
    'BearFramework\App\Request\FormDataFileItem' => 'src/App/Request/FormDataFileItem.php',
    'BearFramework\App\Request\FormDataRepository' => 'src/App/Request/FormDataRepository.php',
    'BearFramework\App\Request\Header' => 'src/App/Request/Header.php',
    'BearFramework\App\Request\HeadersRepository' => 'src/App/Request/HeadersRepository.php',
    'BearFramework\App\Request\PathRepository' => 'src/App/Request/PathRepository.php',
    'BearFramework\App\Request\QueryItem' => 'src/App/Request/QueryItem.php',
    'BearFramework\App\Request\QueryRepository' => 'src/App/Request/QueryRepository.php',
    'BearFramework\App\Response' => 'src/App/Response.php',
    'BearFramework\App\Response\Cookie' => 'src/App/Response/Cookie.php',
    'BearFramework\App\Response\CookiesRepository' => 'src/App/Response/CookiesRepository.php',
    'BearFramework\App\Response\FileReader' => 'src/App/Response/FileReader.php',
    'BearFramework\App\Response\HTML' => 'src/App/Response/HTML.php',
    'BearFramework\App\Response\Header' => 'src/App/Response/Header.php',
    'BearFramework\App\Response\HeadersRepository' => 'src/App/Response/HeadersRepository.php',
    'BearFramework\App\Response\JSON' => 'src/App/Response/JSON.php',
    'BearFramework\App\Response\NotFound' => 'src/App/Response/NotFound.php',
    'BearFramework\App\Response\PermanentRedirect' => 'src/App/Response/PermanentRedirect.php',
    'BearFramework\App\Response\TemporaryRedirect' => 'src/App/Response/TemporaryRedirect.php',
    'BearFramework\App\Response\TemporaryUnavailable' => 'src/App/Response/TemporaryUnavailable.php',
    'BearFramework\App\Response\Text' => 'src/App/Response/Text.php',
    'BearFramework\App\RoutesRepository' => 'src/App/RoutesRepository.php',
    'BearFramework\App\SendResponseEvent' => 'src/App/SendResponseEvent.php',
    'BearFramework\App\ShortcutsRepository' => 'src/App/ShortcutsRepository.php',
    'BearFramework\App\Urls' => 'src/App/Urls.php',
    'BearFramework\Addon' => 'src/Addon.php',
    'BearFramework\Addons' => 'src/Addons.php',
    'BearFramework\App' => 'src/App.php',
    'BearFramework\DataList' => 'src/DataList.php',
    'BearFramework\DataListContext' => 'src/DataListContext.php',
    'BearFramework\DataObject' => 'src/DataObject.php',
];

spl_autoload_register(function ($class) use ($classes) {
    if (isset($classes[$class])) {
        require __DIR__ . '/' . $classes[$class];
    }
}, true);
